### ISSUE TITLE
在单体服务中，feign接口通过http请求；服务合并后，feign接口通过内部进程的方式通信。这个机制的实现方式能麻烦具体说说吗?

### ISSUE THREAD

**Issue by zxxfire** [smart-cloud/smart-cloud#3]
在单体服务中，feign接口通过http请求；服务合并后，feign接口通过内部进程的方式通信.这个机制的实现方式能麻烦具体说说吗?

**Comment by luckyQing** [comment]
https://github.com/smart-cloud/smart-cloud#%E5%9B%9B%E6%9C%8D%E5%8A%A1%E5%90%88%E5%B9%B6%E5%8E%9F%E7%90%86
