### ISSUE TITLE
拆分过渡了

### ISSUE THREAD

**Issue by myoldhome** [smart-cloud/smart-cloud#6]
微服务拆分原则

以业务模型切入，比如：订单管理、商品管理等。
单一职责、高内聚：单个微服务的职责尽量单一。但是粒度要适中，不能过度拆分，过度拆分是微服务架构的灾难！
充分考虑团队结构：微服务的拆分要充分的考虑团队的结构，与微服务开发运维之间的关系。
演进式拆分：如果各方面资源不允许，可以考虑演进式拆分。
避免环形依赖与双向依赖：避免微服务之间的环形依赖或者双向依赖。

**Comment by luckyQing** [comment]
比如呢？
