### ISSUE TITLE
我有两个服务， 也算不上微服务，两个服务之间通讯是用FeignClient通讯， 现在想要合并这两个服务，  我可否引用你的smart-cloud-starter-feign模块，实现支持合并部署、拆分部署？

### ISSUE THREAD

**Issue by Muerli** [smart-cloud/smart-cloud#9]

**Comment by luckyQing** [comment]
可以试一下，如果报错解决不了，可以把最核心的代码copy过去
SmartFeignClient
SmartFeignClientCondition

**Comment by luckyQing** [comment]
> _No description provided._

可以试一下，如果报错解决不了，可以把最核心的代码copy过去
SmartFeignClient
SmartFeignClientCondition

**Comment by luckyQing** [comment]
可以试一下，如果报错解决不了，可以把最核心的代码copy过去
SmartFeignClient
SmartFeignClientCondition
